<?php
declare(strict_types=1);

if (PHP_SAPI !== 'cli') { http_response_code(404); exit; }
require_once dirname(__DIR__) . '/app/Core/SchemaManager.php';

// Real HTTP multipart requests exercise is_uploaded_file/move_uploaded_file.
// The server is bound to loopback, protected by a per-run secret, and uses only
// a random disposable database and temporary private document directory.
$config = require dirname(__DIR__) . '/app/config.php';
$db = $config['db'];
if (($config['app']['environment'] ?? '') !== 'local' || !in_array($db['host'], ['127.0.0.1', 'localhost', '::1'], true)) {
    throw new RuntimeException('Broker upload integration requires a local MySQL server.');
}
$options = [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC, PDO::ATTR_EMULATE_PREPARES => false];
$dsn = sprintf('mysql:host=%s;port=%d;charset=utf8mb4', $db['host'], (int) ($db['port'] ?? 3306));
$server = new PDO($dsn, (string) $db['user'], (string) $db['pass'], $options);
$testName = 'locus_broker_upload_test_' . bin2hex(random_bytes(8));
$directory = sys_get_temp_dir() . '/locus-broker-upload-' . bin2hex(random_bytes(8));
mkdir($directory);
$paths = [];
$process = null;
$created = false;
$checks = 0;
$check = static function (bool $condition, string $message) use (&$checks): void {
    if (!$condition) { throw new RuntimeException($message); }
    $checks++;
};
try {
    $server->exec('CREATE DATABASE `' . $testName . '` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');
    $created = true;
    $pdo = new PDO($dsn . ';dbname=' . $testName, (string) $db['user'], (string) $db['pass'], $options);
    App\Core\SchemaManager::ensure($pdo);
    $pdo->exec("INSERT INTO users(role,name,email,password_hash) VALUES('seller','Upload Broker','upload@example.test','unusable-fixture-password')");
    $id = (int) $pdo->lastInsertId();
    $imagePath = $directory . '/fixture.png';
    $paths[] = $imagePath;
    // Known PNG is generated by the separately GD-enabled fixture server below.
    $invalidPath = $directory . '/invalid.png';
    file_put_contents($invalidPath, '<?php echo "untrusted"; ?>');
    $paths[] = $invalidPath;
    $oversizePath = $directory . '/oversized.png';
    $stream = fopen($oversizePath, 'wb');
    ftruncate($stream, 5 * 1024 * 1024 + 1);
    fclose($stream);
    $paths[] = $oversizePath;
    $secret = bin2hex(random_bytes(32));
    $settingsPath = $directory . '/settings.php';
    file_put_contents($settingsPath, '<?php return ' . var_export(['dsn' => $dsn . ';dbname=' . $testName, 'user' => (string) $db['user'], 'pass' => (string) $db['pass'], 'root' => dirname(__DIR__), 'directory' => $directory . '/private', 'secret' => $secret, 'userId' => $id, 'image' => $imagePath], true) . ';');
    $paths[] = $settingsPath;
    $routerPath = $directory . '/router.php';
    file_put_contents($routerPath, <<<'PHP'
<?php
declare(strict_types=1);
$settings = require __DIR__ . '/settings.php';
if (!hash_equals($settings['secret'], (string) ($_SERVER['HTTP_X_FIXTURE_SECRET'] ?? ''))) { http_response_code(403); exit; }
header('Content-Type: application/json');
if ($_SERVER['REQUEST_METHOD'] === 'GET') {
    if (!function_exists('imagecreatefromstring')) { http_response_code(500); echo '{"error":"GD unavailable"}'; exit; }
    $image = imagecreatetruecolor(32, 20);
    imagefilledrectangle($image, 0, 0, 31, 19, imagecolorallocate($image, 255, 255, 255));
    imagepng($image, $settings['image']);
    imagedestroy($image);
    echo '{"ready":true}'; exit;
}
require $settings['root'] . '/app/Support/helpers.php';
require $settings['root'] . '/app/Repositories/SellerProfileRepository.php';
require $settings['root'] . '/app/Support/BrokerApplicationService.php';
$pdo = new PDO($settings['dsn'], $settings['user'], $settings['pass'], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC, PDO::ATTR_EMULATE_PREPARES => false]);
$documents = new App\Support\BrokerDocuments($settings['directory']);
$profiles = new App\Repositories\SellerProfileRepository($pdo, $documents);
$workflow = new App\Support\BrokerApplicationService($pdo, $profiles, $documents);
try {
    echo json_encode(['profile' => $workflow->saveForUser($settings['userId'], $_POST, $_FILES, true)], JSON_THROW_ON_ERROR);
} catch (InvalidArgumentException $exception) {
    http_response_code(400); echo json_encode(['error' => $exception->getMessage()]);
} catch (Throwable $exception) {
    http_response_code(500); echo json_encode(['error' => $exception->getMessage()]);
}
PHP);
    $paths[] = $routerPath;
    $logPath = $directory . '/server.log';
    $paths[] = $logPath;
    $socket = stream_socket_server('tcp://127.0.0.1:0', $errno, $error);
    if ($socket === false) { throw new RuntimeException('Unable to allocate a loopback test port.'); }
    $address = stream_socket_get_name($socket, false);
    fclose($socket);
    $command = [PHP_BINARY];
    if (!function_exists('imagecreatefromstring')) { array_push($command, '-d', 'extension=gd'); }
    array_push($command, '-d', 'display_errors=0', '-d', 'upload_max_filesize=6M', '-d', 'post_max_size=14M', '-S', $address, $routerPath);
    $process = proc_open($command, [0 => ['pipe', 'r'], 1 => ['file', $logPath, 'a'], 2 => ['file', $logPath, 'a']], $pipes, $directory, null, ['bypass_shell' => true]);
    if (!is_resource($process)) { throw new RuntimeException('Unable to start the isolated upload test server.'); }
    fclose($pipes[0]);
    $request = static function (?array $body = null) use ($address, $secret): array {
        $curl = curl_init('http://' . $address . '/upload');
        curl_setopt_array($curl, [CURLOPT_RETURNTRANSFER => true, CURLOPT_CONNECTTIMEOUT_MS => 200, CURLOPT_TIMEOUT_MS => 5000, CURLOPT_HTTPHEADER => ['X-Fixture-Secret: ' . $secret], CURLOPT_PROXY => '']);
        if ($body !== null) { curl_setopt_array($curl, [CURLOPT_POST => true, CURLOPT_POSTFIELDS => $body]); }
        $response = curl_exec($curl);
        $status = curl_getinfo($curl, CURLINFO_HTTP_CODE);
        curl_close($curl);
        return [$status, is_string($response) ? json_decode($response, true) : null];
    };
    $ready = false;
    for ($attempt = 0; $attempt < 50; $attempt++) {
        [$status, $body] = $request();
        if ($status === 200 && ($body['ready'] ?? false)) { $ready = true; break; }
        usleep(20000);
    }
    $check($ready, 'The isolated multipart test server did not become ready with GD enabled.');
    $payload = ['seller_type' => 'broker', 'legal_name' => 'Upload Broker', 'phone' => '09171234569', 'address_line' => 'Test address', 'city' => 'San Fernando', 'authorization_basis' => 'Licensed real estate broker', 'prc_registration_no' => '875421', 'prc_valid_until' => '2099-12-31'];
    $countDocuments = static fn (): int => count(glob($directory . '/private/*.bin') ?: []);
    [$status, $body] = $request($payload + ['prc_front' => new CURLFile($imagePath, 'image/png', 'front.png')]);
    $check($status === 400 && str_contains($body['error'] ?? '', 'back') && $countDocuments() === 0, 'One-sided multipart submission left a staged document or succeeded (HTTP ' . $status . '; ' . ($body['error'] ?? 'no parsed error') . ').');
    [$status, $body] = $request($payload + ['prc_front' => new CURLFile($imagePath, 'application/pdf', 'spoofed.php'), 'prc_back' => new CURLFile($imagePath, 'image/jpeg', 'back.jpg')]);
    $profile = $body['profile'] ?? [];
    $check($status === 200 && ($profile['applicationStatus'] ?? '') === 'pending_review' && ($profile['frontDocument']['mime'] ?? '') === 'image/png' && ($profile['backDocument']['mime'] ?? '') === 'image/png', 'Real multipart upload did not validate actual image bytes independently of browser claims.');
    $check($countDocuments() === 2 && !str_contains(json_encode($profile), $directory), 'Private documents were not stored exclusively in private temporary storage.');
    $frontId = $profile['frontDocument']['id'];
    $pdo->exec("INSERT INTO users(role,name,email,password_hash) VALUES('seller','Other Upload Broker','other-upload@example.test','unusable-fixture-password')");
    $otherId = (int) $pdo->lastInsertId();
    $pdo->exec("INSERT INTO seller_profiles(user_id,seller_type,legal_name,prc_registration_no) VALUES(" . $otherId . ",'broker','Other Upload Broker','875422')");
    [$status, $body] = $request(array_replace($payload, ['prc_registration_no' => '875422']) + ['prc_front' => new CURLFile($imagePath, 'image/png', 'front.png'), 'prc_back' => new CURLFile($imagePath, 'image/png', 'back.png')]);
    $check($status === 400 && $countDocuments() === 2 && is_file($directory . '/private/' . $frontId . '.bin'), 'A duplicate-license save failure retained staged documents or replaced prior credentials.');
    [$status, $body] = $request($payload + ['prc_front' => new CURLFile($imagePath, 'image/png', 'front.png'), 'prc_back' => new CURLFile($invalidPath, 'image/png', 'back.png')]);
    $check($status === 400 && $countDocuments() === 2 && is_file($directory . '/private/' . $frontId . '.bin'), 'A bad second image deleted prior credentials or retained staged uploads.');
    [$status, $body] = $request($payload + ['prc_front' => new CURLFile($oversizePath, 'image/png', 'front.png')]);
    $check($status === 400 && str_contains($body['error'] ?? '', '5 MB') && $countDocuments() === 2, 'Actual byte limit was not enforced for multipart credentials.');
    $statement = $pdo->query('SELECT application_revision, prc_front_json FROM seller_profiles WHERE user_id = ' . $id);
    $row = $statement->fetch();
    $check((int) $row['application_revision'] === 1 && json_decode($row['prc_front_json'], true)['id'] === $frontId, 'Failed upload requests changed the committed application.');
} finally {
    if (is_resource($process)) { proc_terminate($process); proc_close($process); }
    if ($created) { $server->exec('DROP DATABASE `' . $testName . '`'); }
    // Every deletion target was generated under the explicitly created temp directory.
    foreach (glob($directory . '/private/*.bin') ?: [] as $path) { unlink($path); }
    if (is_file($directory . '/private/.htaccess')) { unlink($directory . '/private/.htaccess'); }
    if (is_dir($directory . '/private')) { rmdir($directory . '/private'); }
    foreach ($paths as $path) { if (is_file($path)) { unlink($path); } }
    if (is_dir($directory)) { rmdir($directory); }
}
echo "Passed {$checks} actual multipart broker upload checks (loopback and disposable database only).\n";
