const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
  const { policyScore, potentialIncentive, priorityActivity } = await import('data:text/javascript;base64,' + Buffer.from(fs.readFileSync('assets/js/investment-policy.js','utf8')).toString('base64'));
  const policy = { policy_priority_adjustment_percent:10, priority_modifier_approved:false, incentives_verified:false, incentive_thresholds:{tier1_min_capital:15000000,tier1_exemption_years:1,tier2_min_capital:3000000,tier2_max_capital:14999999,tier2_discount_percent:10},business_types:[{id:'ict',sector:'ICT'}] };
  const activity = priorityActivity(policy,'ict');
  assert.equal(priorityActivity(policy,'invalid'),null);
  for (const base of [null,undefined,'',NaN,Infinity]) assert.equal(policyScore(base,activity,policy).final,null);
  assert.equal(policyScore(75,activity,policy).final,75,'Unapproved modifier must not change IAI');
  policy.priority_modifier_approved = true;
  assert.equal(policyScore(75,activity,policy).final,75,'Missing approval reference must not enable modifier');
  policy.priority_modifier_approval_reference='test-approved-research';
  assert.deepEqual(policyScore(75,activity,policy),{base:75,percent:10,adjustment:7.5,applied:7.5,final:82.5});
  assert.deepEqual(policyScore(98,activity,policy),{base:98,percent:10,adjustment:9.8,applied:2,final:100},'Show only points actually applied after cap');
  assert.equal(policyScore(0,activity,policy).final,0);
  assert.equal(policyScore(75,{sector:null},policy).final,75);
  assert.equal(potentialIncentive(15000000,policy).badge,'Subject to verification');
  policy.incentives_verified=true;
  assert.equal(potentialIncentive(15000000,policy).badge,'Potential exemption');
  assert.equal(potentialIncentive(14999999,policy).badge,'Potential discount');
  assert.equal(potentialIncentive(14999999.01,policy).badge,'LGU clarification needed');
  assert.equal(potentialIncentive(14999999.99,policy).eligible,false,'Do not widen the ordinance’s stated upper boundary');
  assert.equal(potentialIncentive(3000000,policy).badge,'Potential discount');
  assert.equal(potentialIncentive(2999999.99,policy).badge,'Small enterprise review');
  assert.equal(potentialIncentive(0,policy).badge,'Small enterprise review');
  for (const capital of ['',null,-1,Infinity,'abc']) assert.equal(potentialIncentive(capital,policy).eligible,false);
  assert.equal(potentialIncentive(15000000,{incentives_verified:true}).badge,'Subject to verification','Incomplete configuration must not estimate an incentive');
  console.log('PASS: policy approval gates, null/zero/capped scores and incentive threshold boundaries.');
})().catch(error=>{console.error(error);process.exitCode=1;});
